# auth-service 服务配置
server:
  name: "auth-service"
  addr: "127.0.0.1:8080"

# 日志配置
zap:
  debugFileName: "E:\\CPPToGo\\IM-System\\logs\\debug\\project-debug.log"
  infoFileName: "E:\\CPPToGo\\IM-System\\logs\\info\\project-info.log"
  warnFileName: "E:\\CPPToGo\\IM-System\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3

# redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

# grpc 配置
grpc:
  addr: "127.0.0.1:8881"
  name: "auth-service"